#!/usr/bin/env bash
set -euo pipefail

WEB_USER="${WEB_USER:-arcboxweb}"
WEB_PASSWORD="${WEB_PASSWORD:?WEB_PASSWORD env var must be set}"
WEB_DB="${WEB_DB:-arcboxdemo}"
ALLOW_CIDR="${ALLOW_CIDR:-10.10.1.0/24}"

if [[ ! "${WEB_USER}" =~ ^[a-z_][a-z0-9_]*$ ]]; then
    echo "WEB_USER must be a lowercase PostgreSQL identifier" >&2
    exit 1
fi
if [[ ! "${WEB_DB}" =~ ^[a-z_][a-z0-9_]*$ ]]; then
    echo "WEB_DB must be a lowercase PostgreSQL identifier" >&2
    exit 1
fi

SQL_PASSWORD=$(printf "%s" "${WEB_PASSWORD}" | sed "s/'/''/g")

export DEBIAN_FRONTEND=noninteractive

wait_for_apt_locks() {
    while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
          sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || \
          sudo fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || \
          sudo fuser /var/cache/apt/archives/lock >/dev/null 2>&1; do
        echo 'Waiting for apt/dpkg locks to clear'
        sleep 10
    done
}

run_apt_with_retry() {
    local attempt=1
    local max_attempts=5

    while (( attempt <= max_attempts )); do
        wait_for_apt_locks
        sudo dpkg --configure -a >/dev/null 2>&1 || true
        if sudo apt-get -o DPkg::Lock::Timeout=300 "$@"; then
            return 0
        fi

        echo "apt-get $* failed on attempt ${attempt}/${max_attempts}" >&2
        sudo apt-get install -f -y >/dev/null 2>&1 || true
        ((attempt++))
        sleep 15
    done

    echo "apt-get $* failed after ${max_attempts} attempts" >&2
    return 1
}

echo 'Updating apt and installing PostgreSQL, Apache, Java, and Tomcat'
run_apt_with_retry update
run_apt_with_retry install -y postgresql postgresql-contrib apache2

if apt-cache show tomcat10 >/dev/null 2>&1; then
    TOMCAT_PACKAGE='tomcat10'
else
    TOMCAT_PACKAGE='tomcat9'
fi
TOMCAT_SERVICE="${TOMCAT_PACKAGE}"
TOMCAT_BASE="/var/lib/${TOMCAT_PACKAGE}"

run_apt_with_retry install -y default-jdk "${TOMCAT_PACKAGE}" libpostgresql-jdbc-java curl

PG_VERSION=$(ls /etc/postgresql 2>/dev/null | sort -V | tail -n 1)
PG_CONF="/etc/postgresql/${PG_VERSION}/main/postgresql.conf"
PG_HBA="/etc/postgresql/${PG_VERSION}/main/pg_hba.conf"

echo "Configuring PostgreSQL ${PG_VERSION} to listen on 0.0.0.0"
sudo sed -i "s/^#\?listen_addresses.*/listen_addresses = '*'/" "${PG_CONF}"
if ! sudo grep -qE "host\s+all\s+all\s+${ALLOW_CIDR//\//\/}\s+md5" "${PG_HBA}"; then
    echo "host    all             all             ${ALLOW_CIDR}            md5" | sudo tee -a "${PG_HBA}" > /dev/null
fi
sudo systemctl restart postgresql

echo 'Provisioning PostgreSQL role and database'
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${WEB_USER}') THEN
        CREATE ROLE ${WEB_USER} WITH LOGIN PASSWORD '${SQL_PASSWORD}';
    ELSE
        ALTER ROLE ${WEB_USER} WITH LOGIN PASSWORD '${SQL_PASSWORD}';
    END IF;
END
\$\$;
SELECT 'CREATE DATABASE ${WEB_DB} OWNER ${WEB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${WEB_DB}')\gexec
SQL

echo 'Creating AdventureWorksLT-compatible PostgreSQL schema'
sudo -u postgres psql -d "${WEB_DB}" -v ON_ERROR_STOP=1 <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS dbo;
CREATE SCHEMA IF NOT EXISTS saleslt;

CREATE TABLE IF NOT EXISTS dbo.build_version (
    system_information_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    database_version varchar(25) NOT NULL,
    version_date timestamp NOT NULL,
    modified_date timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbo.error_log (
    error_log_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_time timestamp NOT NULL DEFAULT now(),
    user_name varchar(128) NOT NULL,
    error_number integer NOT NULL,
    error_severity integer NULL,
    error_state integer NULL,
    error_procedure varchar(126) NULL,
    error_line integer NULL,
    error_message varchar(4000) NOT NULL
);

CREATE TABLE IF NOT EXISTS saleslt.address (
    address_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_line1 varchar(60) NOT NULL,
    address_line2 varchar(60) NULL,
    city varchar(30) NOT NULL,
    state_province varchar(50) NOT NULL,
    country_region varchar(50) NOT NULL,
    postal_code varchar(15) NOT NULL,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_address_state_province ON saleslt.address(state_province);

CREATE TABLE IF NOT EXISTS saleslt.customer (
    customer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_style boolean NOT NULL DEFAULT false,
    title varchar(8) NULL,
    first_name varchar(50) NOT NULL,
    middle_name varchar(50) NULL,
    last_name varchar(50) NOT NULL,
    suffix varchar(10) NULL,
    company_name varchar(128) NULL,
    sales_person varchar(256) NULL,
    email_address varchar(50) NULL,
    phone varchar(25) NULL,
    password_hash varchar(128) NOT NULL DEFAULT 'legacy-demo-hash',
    password_salt varchar(10) NOT NULL DEFAULT 'demo',
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_customer_email_address ON saleslt.customer(email_address);

CREATE TABLE IF NOT EXISTS saleslt.customer_address (
    customer_id integer NOT NULL REFERENCES saleslt.customer(customer_id),
    address_id integer NOT NULL REFERENCES saleslt.address(address_id),
    address_type varchar(50) NOT NULL,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY (customer_id, address_id)
);

CREATE TABLE IF NOT EXISTS saleslt.product_category (
    product_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_category_id integer NULL REFERENCES saleslt.product_category(product_category_id),
    name varchar(50) NOT NULL UNIQUE,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS saleslt.product_model (
    product_model_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    catalog_description text NULL,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS saleslt.product_description (
    product_description_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(400) NOT NULL,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS saleslt.product_model_product_description (
    product_model_id integer NOT NULL REFERENCES saleslt.product_model(product_model_id),
    product_description_id integer NOT NULL REFERENCES saleslt.product_description(product_description_id),
    culture char(6) NOT NULL,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY (product_model_id, product_description_id, culture)
);

CREATE TABLE IF NOT EXISTS saleslt.product (
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    product_number varchar(25) NOT NULL UNIQUE,
    color varchar(15) NULL,
    standard_cost numeric(19,4) NOT NULL CHECK (standard_cost >= 0),
    list_price numeric(19,4) NOT NULL CHECK (list_price >= 0),
    size varchar(5) NULL,
    weight numeric(8,2) NULL,
    product_category_id integer NULL REFERENCES saleslt.product_category(product_category_id),
    product_model_id integer NULL REFERENCES saleslt.product_model(product_model_id),
    sell_start_date timestamp NOT NULL DEFAULT now(),
    sell_end_date timestamp NULL,
    discontinued_date timestamp NULL,
    thumbnail_photo bytea NULL,
    thumbnail_photo_file_name varchar(50) NULL,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_product_name ON saleslt.product(name);
CREATE INDEX IF NOT EXISTS ix_product_category ON saleslt.product(product_category_id);

CREATE TABLE IF NOT EXISTS saleslt.sales_order_header (
    sales_order_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_number smallint NOT NULL DEFAULT 0,
    order_date timestamp NOT NULL DEFAULT now(),
    due_date timestamp NOT NULL DEFAULT (now() + interval '7 days'),
    ship_date timestamp NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status BETWEEN 1 AND 6),
    online_order_flag boolean NOT NULL DEFAULT true,
    sales_order_number varchar(25) NULL,
    purchase_order_number varchar(25) NULL,
    account_number varchar(15) NULL,
    customer_id integer NOT NULL REFERENCES saleslt.customer(customer_id),
    ship_to_address_id integer NULL REFERENCES saleslt.address(address_id),
    bill_to_address_id integer NULL REFERENCES saleslt.address(address_id),
    ship_method varchar(50) NOT NULL DEFAULT 'CARGO TRANSPORT 5',
    credit_card_approval_code varchar(15) NULL,
    subtotal numeric(19,4) NOT NULL DEFAULT 0,
    tax_amt numeric(19,4) NOT NULL DEFAULT 0,
    freight numeric(19,4) NOT NULL DEFAULT 0,
    total_due numeric(19,4) GENERATED ALWAYS AS (subtotal + tax_amt + freight) STORED,
    comment text NULL,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_sales_order_header_customer ON saleslt.sales_order_header(customer_id);

CREATE TABLE IF NOT EXISTS saleslt.sales_order_detail (
    sales_order_id integer NOT NULL REFERENCES saleslt.sales_order_header(sales_order_id) ON DELETE CASCADE,
    sales_order_detail_id integer GENERATED BY DEFAULT AS IDENTITY,
    order_qty smallint NOT NULL CHECK (order_qty > 0),
    product_id integer NOT NULL REFERENCES saleslt.product(product_id),
    unit_price numeric(19,4) NOT NULL CHECK (unit_price >= 0),
    unit_price_discount numeric(19,4) NOT NULL DEFAULT 0 CHECK (unit_price_discount >= 0),
    line_total numeric(19,4) GENERATED ALWAYS AS ((unit_price * (1 - unit_price_discount)) * order_qty) STORED,
    rowguid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    modified_date timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY (sales_order_id, sales_order_detail_id)
);
CREATE INDEX IF NOT EXISTS ix_sales_order_detail_product ON saleslt.sales_order_detail(product_id);

CREATE OR REPLACE VIEW saleslt.v_storefront_catalog AS
SELECT p.product_id, p.name, p.product_number, p.color, p.size, p.weight, p.standard_cost, p.list_price,
       c.name AS category_name, pm.name AS product_model, pd.description
FROM saleslt.product p
LEFT JOIN saleslt.product_category c ON c.product_category_id = p.product_category_id
LEFT JOIN saleslt.product_model pm ON pm.product_model_id = p.product_model_id
LEFT JOIN LATERAL (
    SELECT d.description
    FROM saleslt.product_model_product_description x
    INNER JOIN saleslt.product_description d ON d.product_description_id = x.product_description_id
    WHERE x.product_model_id = p.product_model_id
    ORDER BY CASE WHEN x.culture = 'en' THEN 0 ELSE 1 END, x.culture
    LIMIT 1
) pd ON true;

CREATE OR REPLACE VIEW saleslt.v_customer_orders AS
SELECT c.customer_id, c.first_name, c.last_name, c.company_name, c.email_address,
       h.sales_order_id, h.sales_order_number, h.order_date, h.status, h.total_due
FROM saleslt.customer c
LEFT JOIN saleslt.sales_order_header h ON h.customer_id = c.customer_id;

CREATE OR REPLACE FUNCTION saleslt.recalculate_order_totals()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    changed_order_id integer;
    new_subtotal numeric(19,4);
BEGIN
    changed_order_id := COALESCE(NEW.sales_order_id, OLD.sales_order_id);
    SELECT COALESCE(SUM(line_total), 0) INTO new_subtotal
    FROM saleslt.sales_order_detail
    WHERE sales_order_id = changed_order_id;

    UPDATE saleslt.sales_order_header
    SET subtotal = new_subtotal,
        tax_amt = round(new_subtotal * 0.0825, 4),
        freight = CASE WHEN new_subtotal = 0 THEN 0 ELSE round(12.50 + (new_subtotal * 0.015), 4) END,
        modified_date = now()
    WHERE sales_order_id = changed_order_id;

    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE OR REPLACE FUNCTION saleslt.set_sales_order_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.sales_order_number IS NULL THEN
        NEW.sales_order_number := 'SO' || NEW.sales_order_id::text;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_sales_order_number ON saleslt.sales_order_header;
CREATE TRIGGER trg_set_sales_order_number
BEFORE INSERT ON saleslt.sales_order_header
FOR EACH ROW EXECUTE FUNCTION saleslt.set_sales_order_number();

DROP TRIGGER IF EXISTS trg_recalculate_order_totals ON saleslt.sales_order_detail;
CREATE TRIGGER trg_recalculate_order_totals
AFTER INSERT OR UPDATE OR DELETE ON saleslt.sales_order_detail
FOR EACH ROW EXECUTE FUNCTION saleslt.recalculate_order_totals();
SQL

echo 'Seeding AdventureWorksLT PostgreSQL data'
sudo -u postgres psql -d "${WEB_DB}" -v ON_ERROR_STOP=1 <<'SQL'
INSERT INTO dbo.build_version (database_version, version_date)
SELECT 'AdventureWorksLT-PG', now()
WHERE NOT EXISTS (SELECT 1 FROM dbo.build_version WHERE database_version = 'AdventureWorksLT-PG');

WITH roots(name) AS (
    VALUES ('Bikes'), ('Components'), ('Clothing'), ('Accessories')
)
INSERT INTO saleslt.product_category (name)
SELECT name FROM roots
ON CONFLICT (name) DO NOTHING;

WITH children(parent_name, name) AS (
    VALUES
    ('Bikes', 'Mountain Bikes'),
    ('Bikes', 'Road Bikes'),
    ('Bikes', 'Touring Bikes'),
    ('Components', 'Handlebars'),
    ('Components', 'Saddles'),
    ('Components', 'Wheels'),
    ('Clothing', 'Jerseys'),
    ('Clothing', 'Gloves'),
    ('Accessories', 'Helmets'),
    ('Accessories', 'Hydration Packs'),
    ('Accessories', 'Lights')
)
INSERT INTO saleslt.product_category (parent_product_category_id, name)
SELECT parent.product_category_id, children.name
FROM children
JOIN saleslt.product_category parent ON parent.name = children.parent_name
ON CONFLICT (name) DO NOTHING;

WITH model_seed(name, description) AS (
    VALUES
    ('Mountain-500', 'Aluminum mountain bike for trail riding, rentals, and commuter abuse.'),
    ('Road-750', 'Lightweight road bike with endurance geometry and dependable components.'),
    ('Touring-3000', 'Long-range touring bike with integrated rack mounts and comfort fit.'),
    ('Sport Helmet', 'Ventilated helmet with removable visor and dial-fit retention.'),
    ('Hydration Pack', 'Low-profile pack with reservoir, tool pockets, and reflective trim.'),
    ('Classic Jersey', 'Legacy club-fit jersey with durable full-length zipper.'),
    ('Ergo Saddle', 'Comfort saddle with chromoly rails and pressure relief channel.'),
    ('LED Light Set', 'USB rechargeable headlight and taillight pair for mixed commuting.')
)
INSERT INTO saleslt.product_model (name, catalog_description)
SELECT name, description FROM model_seed
ON CONFLICT (name) DO NOTHING;

WITH model_seed(name, description) AS (
    VALUES
    ('Mountain-500', 'Aluminum mountain bike for trail riding, rentals, and commuter abuse.'),
    ('Road-750', 'Lightweight road bike with endurance geometry and dependable components.'),
    ('Touring-3000', 'Long-range touring bike with integrated rack mounts and comfort fit.'),
    ('Sport Helmet', 'Ventilated helmet with removable visor and dial-fit retention.'),
    ('Hydration Pack', 'Low-profile pack with reservoir, tool pockets, and reflective trim.'),
    ('Classic Jersey', 'Legacy club-fit jersey with durable full-length zipper.'),
    ('Ergo Saddle', 'Comfort saddle with chromoly rails and pressure relief channel.'),
    ('LED Light Set', 'USB rechargeable headlight and taillight pair for mixed commuting.')
)
INSERT INTO saleslt.product_description (description)
SELECT description FROM model_seed
WHERE NOT EXISTS (SELECT 1 FROM saleslt.product_description d WHERE d.description = model_seed.description);

WITH model_seed(name, description) AS (
    VALUES
    ('Mountain-500', 'Aluminum mountain bike for trail riding, rentals, and commuter abuse.'),
    ('Road-750', 'Lightweight road bike with endurance geometry and dependable components.'),
    ('Touring-3000', 'Long-range touring bike with integrated rack mounts and comfort fit.'),
    ('Sport Helmet', 'Ventilated helmet with removable visor and dial-fit retention.'),
    ('Hydration Pack', 'Low-profile pack with reservoir, tool pockets, and reflective trim.'),
    ('Classic Jersey', 'Legacy club-fit jersey with durable full-length zipper.'),
    ('Ergo Saddle', 'Comfort saddle with chromoly rails and pressure relief channel.'),
    ('LED Light Set', 'USB rechargeable headlight and taillight pair for mixed commuting.')
)
INSERT INTO saleslt.product_model_product_description (product_model_id, product_description_id, culture)
SELECT pm.product_model_id, pd.product_description_id, 'en'
FROM model_seed seed
JOIN saleslt.product_model pm ON pm.name = seed.name
JOIN saleslt.product_description pd ON pd.description = seed.description
ON CONFLICT (product_model_id, product_description_id, culture) DO NOTHING;

WITH product_seed(name, product_number, color, standard_cost, list_price, size, weight, category_name, model_name) AS (
    VALUES
    ('Mountain-500 Black, 44', 'BK-M18B-44', 'Black', 294.58, 539.99, '44', 29.20, 'Mountain Bikes', 'Mountain-500'),
    ('Mountain-500 Silver, 48', 'BK-M18S-48', 'Silver', 308.22, 564.99, '48', 29.80, 'Mountain Bikes', 'Mountain-500'),
    ('Road-750 Black, 52', 'BK-R19B-52', 'Black', 419.78, 874.99, '52', 20.42, 'Road Bikes', 'Road-750'),
    ('Road-750 Red, 58', 'BK-R19R-58', 'Red', 430.14, 899.99, '58', 20.94, 'Road Bikes', 'Road-750'),
    ('Touring-3000 Blue, 54', 'BK-T18B-54', 'Blue', 461.44, 742.35, '54', 25.10, 'Touring Bikes', 'Touring-3000'),
    ('Sport-100 Helmet, Black', 'HL-U509-B', 'Black', 13.09, 34.99, NULL, NULL, 'Helmets', 'Sport Helmet'),
    ('Sport-100 Helmet, Red', 'HL-U509-R', 'Red', 13.09, 34.99, NULL, NULL, 'Helmets', 'Sport Helmet'),
    ('Hydration Pack - 70 oz.', 'HY-1023-70', 'Silver', 20.57, 54.99, '70', 1.20, 'Hydration Packs', 'Hydration Pack'),
    ('Classic Vest, S', 'VE-C304-S', 'Blue', 23.75, 63.50, 'S', 0.70, 'Jerseys', 'Classic Jersey'),
    ('Ergo Touring Saddle', 'SE-T924', 'Black', 24.11, 49.99, NULL, 1.10, 'Saddles', 'Ergo Saddle'),
    ('Front and Tail Light Set', 'LT-T990', 'Black', 18.20, 44.95, NULL, 0.40, 'Lights', 'LED Light Set')
)
INSERT INTO saleslt.product (name, product_number, color, standard_cost, list_price, size, weight, product_category_id, product_model_id, sell_start_date)
SELECT seed.name, seed.product_number, seed.color, seed.standard_cost, seed.list_price, seed.size, seed.weight, category.product_category_id, model.product_model_id, now() - interval '30 days'
FROM product_seed seed
JOIN saleslt.product_category category ON category.name = seed.category_name
JOIN saleslt.product_model model ON model.name = seed.model_name
ON CONFLICT (product_number) DO NOTHING;

WITH customer_seed(first_name, last_name, company_name, email_address, phone, address_line1, city, state_province, country_region, postal_code) AS (
    VALUES
    ('Orlando', 'Gee', 'A Bike Store', 'orlando.gee@example.com', '245-555-0173', '1970 Napa Ct.', 'Bothell', 'Washington', 'United States', '98011'),
    ('Keith', 'Harris', 'Progressive Sports', 'keith.harris@example.com', '245-555-0187', '9833 Mt. Dias Blv.', 'Portland', 'Oregon', 'United States', '97205'),
    ('Donna', 'Carreras', 'Trailhead Cycles', 'donna.carreras@example.com', '245-555-0149', '4182 Ryder Ave.', 'San Francisco', 'California', 'United States', '94109'),
    ('Janet', 'Gates', 'Modular Cycle Systems', 'janet.gates@example.com', '245-555-0132', '9178 Jumping St.', 'Austin', 'Texas', 'United States', '78701'),
    ('Lucy', 'Harrington', 'Northwind Traders', 'lucy.harrington@example.com', '245-555-0121', '83 Riverside Drive', 'Denver', 'Colorado', 'United States', '80202')
)
INSERT INTO saleslt.customer (first_name, last_name, company_name, email_address, phone)
SELECT first_name, last_name, company_name, email_address, phone
FROM customer_seed seed
WHERE NOT EXISTS (SELECT 1 FROM saleslt.customer existing WHERE existing.email_address = seed.email_address);

WITH customer_seed(first_name, last_name, company_name, email_address, phone, address_line1, city, state_province, country_region, postal_code) AS (
    VALUES
    ('Orlando', 'Gee', 'A Bike Store', 'orlando.gee@example.com', '245-555-0173', '1970 Napa Ct.', 'Bothell', 'Washington', 'United States', '98011'),
    ('Keith', 'Harris', 'Progressive Sports', 'keith.harris@example.com', '245-555-0187', '9833 Mt. Dias Blv.', 'Portland', 'Oregon', 'United States', '97205'),
    ('Donna', 'Carreras', 'Trailhead Cycles', 'donna.carreras@example.com', '245-555-0149', '4182 Ryder Ave.', 'San Francisco', 'California', 'United States', '94109'),
    ('Janet', 'Gates', 'Modular Cycle Systems', 'janet.gates@example.com', '245-555-0132', '9178 Jumping St.', 'Austin', 'Texas', 'United States', '78701'),
    ('Lucy', 'Harrington', 'Northwind Traders', 'lucy.harrington@example.com', '245-555-0121', '83 Riverside Drive', 'Denver', 'Colorado', 'United States', '80202')
)
INSERT INTO saleslt.address (address_line1, city, state_province, country_region, postal_code)
SELECT address_line1, city, state_province, country_region, postal_code
FROM customer_seed seed
WHERE NOT EXISTS (SELECT 1 FROM saleslt.address existing WHERE existing.address_line1 = seed.address_line1 AND existing.postal_code = seed.postal_code);

WITH customer_seed(email_address, address_line1, postal_code) AS (
    VALUES
    ('orlando.gee@example.com', '1970 Napa Ct.', '98011'),
    ('keith.harris@example.com', '9833 Mt. Dias Blv.', '97205'),
    ('donna.carreras@example.com', '4182 Ryder Ave.', '94109'),
    ('janet.gates@example.com', '9178 Jumping St.', '78701'),
    ('lucy.harrington@example.com', '83 Riverside Drive', '80202')
)
INSERT INTO saleslt.customer_address (customer_id, address_id, address_type)
SELECT c.customer_id, a.address_id, 'Main Office'
FROM customer_seed seed
JOIN saleslt.customer c ON c.email_address = seed.email_address
JOIN saleslt.address a ON a.address_line1 = seed.address_line1 AND a.postal_code = seed.postal_code
ON CONFLICT (customer_id, address_id) DO NOTHING;

DO $$
DECLARE
    order_id integer;
    customer_id_value integer;
    address_id_value integer;
    product_id_value integer;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM saleslt.sales_order_header WHERE purchase_order_number = 'PO-100001') THEN
        SELECT c.customer_id, ca.address_id INTO customer_id_value, address_id_value
        FROM saleslt.customer c JOIN saleslt.customer_address ca ON ca.customer_id = c.customer_id
        WHERE c.email_address = 'orlando.gee@example.com' LIMIT 1;
        INSERT INTO saleslt.sales_order_header (purchase_order_number, account_number, customer_id, ship_to_address_id, bill_to_address_id, status, comment)
        VALUES ('PO-100001', '10-4020-000000', customer_id_value, address_id_value, address_id_value, 2, 'Seeded migration demo order')
        RETURNING sales_order_id INTO order_id;
        SELECT product_id INTO product_id_value FROM saleslt.product WHERE product_number = 'BK-M18B-44';
        INSERT INTO saleslt.sales_order_detail (sales_order_id, product_id, order_qty, unit_price)
        SELECT order_id, product_id_value, 1, list_price FROM saleslt.product WHERE product_id = product_id_value;
        SELECT product_id INTO product_id_value FROM saleslt.product WHERE product_number = 'HL-U509-B';
        INSERT INTO saleslt.sales_order_detail (sales_order_id, product_id, order_qty, unit_price)
        SELECT order_id, product_id_value, 2, list_price FROM saleslt.product WHERE product_id = product_id_value;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM saleslt.sales_order_header WHERE purchase_order_number = 'PO-100002') THEN
        SELECT c.customer_id, ca.address_id INTO customer_id_value, address_id_value
        FROM saleslt.customer c JOIN saleslt.customer_address ca ON ca.customer_id = c.customer_id
        WHERE c.email_address = 'keith.harris@example.com' LIMIT 1;
        INSERT INTO saleslt.sales_order_header (purchase_order_number, account_number, customer_id, ship_to_address_id, bill_to_address_id, status, comment)
        VALUES ('PO-100002', '10-4020-000000', customer_id_value, address_id_value, address_id_value, 2, 'Seeded migration demo order')
        RETURNING sales_order_id INTO order_id;
        SELECT product_id INTO product_id_value FROM saleslt.product WHERE product_number = 'BK-R19B-52';
        INSERT INTO saleslt.sales_order_detail (sales_order_id, product_id, order_qty, unit_price)
        SELECT order_id, product_id_value, 2, list_price FROM saleslt.product WHERE product_id = product_id_value;
        SELECT product_id INTO product_id_value FROM saleslt.product WHERE product_number = 'HY-1023-70';
        INSERT INTO saleslt.sales_order_detail (sales_order_id, product_id, order_qty, unit_price)
        SELECT order_id, product_id_value, 2, list_price FROM saleslt.product WHERE product_id = product_id_value;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM saleslt.sales_order_header WHERE purchase_order_number = 'PO-100003') THEN
        SELECT c.customer_id, ca.address_id INTO customer_id_value, address_id_value
        FROM saleslt.customer c JOIN saleslt.customer_address ca ON ca.customer_id = c.customer_id
        WHERE c.email_address = 'donna.carreras@example.com' LIMIT 1;
        INSERT INTO saleslt.sales_order_header (purchase_order_number, account_number, customer_id, ship_to_address_id, bill_to_address_id, status, comment)
        VALUES ('PO-100003', '10-4020-000000', customer_id_value, address_id_value, address_id_value, 2, 'Seeded migration demo order')
        RETURNING sales_order_id INTO order_id;
        SELECT product_id INTO product_id_value FROM saleslt.product WHERE product_number = 'BK-T18B-54';
        INSERT INTO saleslt.sales_order_detail (sales_order_id, product_id, order_qty, unit_price)
        SELECT order_id, product_id_value, 1, list_price FROM saleslt.product WHERE product_id = product_id_value;
    END IF;
END $$;
SQL

echo 'Granting PostgreSQL database permissions to web role'
sudo -u postgres psql -d "${WEB_DB}" -v ON_ERROR_STOP=1 <<SQL
GRANT USAGE ON SCHEMA dbo, saleslt TO ${WEB_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dbo, saleslt TO ${WEB_USER};
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA dbo, saleslt TO ${WEB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${WEB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA saleslt GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${WEB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${WEB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA saleslt GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${WEB_USER};
SQL

: <<'LEGACY_PHP_STOREFRONT_REMOVED'
echo 'Installing retired AdventureWorks storefront payload'
sudo tee /var/www/html/index.php > /dev/null <<'PHP'
<?php
$dbName = '__WEB_DB__';
$dbUser = '__WEB_USER__';
$dbPassword = '__WEB_PASSWORD__';
$message = '';
$error = '';
$validViews = array('catalog', 'products', 'customers', 'orders', 'reports');
$view = isset($_REQUEST['view']) && in_array($_REQUEST['view'], $validViews, true) ? $_REQUEST['view'] : 'catalog';

function h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function money($value) { return '$' . number_format((float)$value, 2); }
function db() {
    global $dbName, $dbUser, $dbPassword;
    static $pdo = null;
    if ($pdo === null) {
        $pdo = new PDO("pgsql:host=localhost;dbname={$dbName}", $dbUser, $dbPassword, array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION));
    }
    return $pdo;
}
function rows($sql, $params = array()) {
    $stmt = db()->prepare($sql);
    $stmt->execute($params);
    return $stmt->fetchAll(PDO::FETCH_ASSOC);
}
function scalar($sql, $params = array()) {
    $stmt = db()->prepare($sql);
    $stmt->execute($params);
    return $stmt->fetchColumn();
}
function required($key, $label) {
    $value = trim(isset($_POST[$key]) ? $_POST[$key] : '');
    if ($value === '') { throw new Exception($label . ' is required.'); }
    return $value;
}
function as_int($key, $label) {
    $value = filter_input(INPUT_POST, $key, FILTER_VALIDATE_INT);
    if ($value === false || $value === null) { throw new Exception($label . ' must be a number.'); }
    return $value;
}
function as_money($key, $label) {
    $value = filter_input(INPUT_POST, $key, FILTER_VALIDATE_FLOAT);
    if ($value === false || $value === null) { throw new Exception($label . ' must be numeric.'); }
    return $value;
}
function options($items, $valueKey, $labelKey, $selected = null) {
    $html = '';
    foreach ($items as $item) {
        $value = $item[$valueKey];
        $html .= '<option value="' . h($value) . '"' . ((string)$selected === (string)$value ? ' selected' : '') . '>' . h($item[$labelKey]) . '</option>';
    }
    return $html;
}
function categories() {
    return rows("SELECT c.product_category_id, COALESCE(parent.name || ' / ', '') || c.name AS label FROM saleslt.product_category c LEFT JOIN saleslt.product_category parent ON parent.product_category_id = c.parent_product_category_id ORDER BY label");
}
function customers() {
    return rows("SELECT customer_id, last_name || ', ' || first_name || COALESCE(' - ' || company_name, '') AS label FROM saleslt.customer ORDER BY last_name, first_name");
}
function products() {
    return rows("SELECT product_id, name || ' - ' || to_char(list_price, 'FM$999,999,990.00') AS label FROM saleslt.product WHERE sell_end_date IS NULL ORDER BY name");
}
function ensure_model($modelName, $description) {
    $modelId = scalar('SELECT product_model_id FROM saleslt.product_model WHERE name = ?', array($modelName));
    if (!$modelId) {
        $stmt = db()->prepare('INSERT INTO saleslt.product_model (name, catalog_description) VALUES (?, ?) RETURNING product_model_id');
        $stmt->execute(array($modelName, $description));
        $modelId = $stmt->fetchColumn();
    }
    $descriptionId = scalar('SELECT product_description_id FROM saleslt.product_description WHERE description = ?', array($description));
    if (!$descriptionId) {
        $stmt = db()->prepare('INSERT INTO saleslt.product_description (description) VALUES (?) RETURNING product_description_id');
        $stmt->execute(array($description));
        $descriptionId = $stmt->fetchColumn();
    }
    db()->prepare("INSERT INTO saleslt.product_model_product_description (product_model_id, product_description_id, culture) VALUES (?, ?, 'en') ON CONFLICT DO NOTHING")->execute(array($modelId, $descriptionId));
    return $modelId;
}

try {
    db();
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        $action = isset($_POST['action']) ? $_POST['action'] : '';
        if ($action === 'saveProduct') {
            $productId = isset($_POST['product_id']) ? (int)$_POST['product_id'] : 0;
            $name = required('name', 'Product name');
            $number = required('product_number', 'Product number');
            $model = required('model_name', 'Product model');
            $description = required('description', 'Description');
            $categoryId = as_int('product_category_id', 'Category');
            $listPrice = as_money('list_price', 'List price');
            $standardCost = round($listPrice * 0.55, 2);
            $modelId = ensure_model($model, $description);
            $weight = trim(isset($_POST['weight']) ? $_POST['weight'] : '') === '' ? null : (float)$_POST['weight'];
            if ($productId > 0) {
                db()->prepare('UPDATE saleslt.product SET name=?, product_number=?, color=?, standard_cost=?, list_price=?, size=?, weight=?, product_category_id=?, product_model_id=?, sell_end_date=NULL, modified_date=now() WHERE product_id=?')
                    ->execute(array($name, $number, $_POST['color'], $standardCost, $listPrice, $_POST['size'], $weight, $categoryId, $modelId, $productId));
            } else {
                db()->prepare('INSERT INTO saleslt.product (name, product_number, color, standard_cost, list_price, size, weight, product_category_id, product_model_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)')
                    ->execute(array($name, $number, $_POST['color'], $standardCost, $listPrice, $_POST['size'], $weight, $categoryId, $modelId));
            }
            $view = 'products'; $message = 'Product saved.';
        } elseif ($action === 'retireProduct') {
            db()->prepare('UPDATE saleslt.product SET sell_end_date=now(), modified_date=now() WHERE product_id=?')->execute(array(as_int('product_id', 'Product')));
            $view = 'products'; $message = 'Product retired.';
        } elseif ($action === 'saveCustomer') {
            $customerId = isset($_POST['customer_id']) ? (int)$_POST['customer_id'] : 0;
            if ($customerId > 0) {
                db()->prepare('UPDATE saleslt.customer SET first_name=?, last_name=?, company_name=?, email_address=?, phone=?, modified_date=now() WHERE customer_id=?')
                    ->execute(array(required('first_name', 'First name'), required('last_name', 'Last name'), $_POST['company_name'], required('email_address', 'Email'), $_POST['phone'], $customerId));
            } else {
                db()->prepare('INSERT INTO saleslt.customer (first_name, last_name, company_name, email_address, phone) VALUES (?, ?, ?, ?, ?)')
                    ->execute(array(required('first_name', 'First name'), required('last_name', 'Last name'), $_POST['company_name'], required('email_address', 'Email'), $_POST['phone']));
            }
            $view = 'customers'; $message = 'Customer saved.';
        } elseif ($action === 'saveAddress') {
            $stmt = db()->prepare('INSERT INTO saleslt.address (address_line1, address_line2, city, state_province, country_region, postal_code) VALUES (?, ?, ?, ?, ?, ?) RETURNING address_id');
            $stmt->execute(array(required('address_line1', 'Address'), $_POST['address_line2'], required('city', 'City'), required('state_province', 'State'), required('country_region', 'Country'), required('postal_code', 'Postal code')));
            $addressId = $stmt->fetchColumn();
            db()->prepare('INSERT INTO saleslt.customer_address (customer_id, address_id, address_type) VALUES (?, ?, ?) ON CONFLICT DO NOTHING')
                ->execute(array(as_int('customer_id', 'Customer'), $addressId, required('address_type', 'Address type')));
            $view = 'customers'; $message = 'Address saved.';
        } elseif ($action === 'createOrder') {
            $customerId = as_int('customer_id', 'Customer');
            $productId = as_int('product_id', 'Product');
            $quantity = as_int('quantity', 'Quantity');
            if ($quantity < 1) { throw new Exception('Quantity must be at least 1.'); }
            $addressId = scalar('SELECT address_id FROM saleslt.customer_address WHERE customer_id=? ORDER BY address_id LIMIT 1', array($customerId));
            if (!$addressId) { throw new Exception('Add a customer address before creating an order.'); }
            $unitPrice = scalar('SELECT list_price FROM saleslt.product WHERE product_id=?', array($productId));
            $stmt = db()->prepare("INSERT INTO saleslt.sales_order_header (customer_id, ship_to_address_id, bill_to_address_id, purchase_order_number, account_number, status, comment) VALUES (?, ?, ?, ?, '10-4020-WEB', 1, 'Created from retired storefront payload') RETURNING sales_order_id");
            $stmt->execute(array($customerId, $addressId, $addressId, 'WEB-' . gmdate('YmdHis')));
            $orderId = $stmt->fetchColumn();
            db()->prepare('INSERT INTO saleslt.sales_order_detail (sales_order_id, product_id, order_qty, unit_price) VALUES (?, ?, ?, ?)')->execute(array($orderId, $productId, $quantity, $unitPrice));
            $view = 'orders'; $message = 'Order created.';
        } elseif ($action === 'updateOrderStatus') {
            db()->prepare('UPDATE saleslt.sales_order_header SET status=?, ship_date=CASE WHEN ? >= 5 THEN COALESCE(ship_date, now()) ELSE ship_date END, modified_date=now() WHERE sales_order_id=?')
                ->execute(array(as_int('status', 'Status'), as_int('status', 'Status'), as_int('sales_order_id', 'Order')));
            $view = 'orders'; $message = 'Order status updated.';
        }
    }
} catch (Exception $ex) {
    $error = $ex->getMessage();
}

$stats = array('products' => 0, 'customers' => 0, 'orders' => 0, 'revenue' => 0);
try {
    $stats['products'] = scalar('SELECT count(*) FROM saleslt.product WHERE sell_end_date IS NULL');
    $stats['customers'] = scalar('SELECT count(*) FROM saleslt.customer');
    $stats['orders'] = scalar('SELECT count(*) FROM saleslt.sales_order_header');
    $stats['revenue'] = scalar('SELECT coalesce(sum(total_due),0) FROM saleslt.sales_order_header');
} catch (Exception $ignore) { }
?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>PostgreSQL AdventureWorks Storefront</title>
    <style>
        :root { --ink:#18211f; --muted:#66736d; --line:#d5ded8; --paper:#fbfaf3; --panel:#fff; --brand:#28615a; --accent:#b85c38; --soft:#edf5ef; }
        * { box-sizing:border-box; }
        body { margin:0; color:var(--ink); font-family:Georgia,"Times New Roman",serif; background:linear-gradient(135deg,#fbfaf3 0%,#edf5ef 50%,#f8e7dc 100%); }
        header, nav, main, footer { width:min(1180px,calc(100% - 30px)); margin:auto; }
        header { padding:30px 0 12px; display:flex; justify-content:space-between; gap:18px; align-items:end; border-bottom:1px solid var(--line); }
        h1 { margin:0; font-size:clamp(2rem,5vw,4rem); line-height:1; }
        h2, h3 { margin:0 0 12px; }
        p { color:var(--muted); line-height:1.5; }
        nav { display:flex; flex-wrap:wrap; gap:8px; padding:18px 0; }
        nav a, button { border:1px solid var(--brand); border-radius:7px; padding:10px 14px; background:#fff; color:var(--brand); text-decoration:none; font:bold .86rem Verdana,sans-serif; cursor:pointer; }
        nav a.active, button { background:var(--brand); color:#fff; }
        .metrics { display:grid; grid-template-columns:repeat(4,minmax(130px,1fr)); gap:12px; margin-bottom:18px; }
        .metric, .panel, .card, .edit-card, .order-card { background:rgba(255,255,255,.92); border:1px solid var(--line); border-radius:8px; box-shadow:0 12px 30px rgba(24,33,31,.08); }
        .metric { padding:16px; }
        .metric span, label, .pill, .small { color:var(--muted); font:.78rem Verdana,sans-serif; }
        .metric strong { display:block; font-size:1.8rem; margin-top:8px; }
        .panel { padding:20px; margin-bottom:16px; }
        .hero { display:grid; grid-template-columns:1fr auto; gap:18px; background:linear-gradient(120deg,#fff,var(--soft)); }
        .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:16px; }
        .card, .edit-card, .order-card { padding:16px; }
        .pill { display:inline-block; background:var(--soft); color:var(--brand); padding:5px 9px; border-radius:999px; margin-bottom:10px; }
        dl { display:grid; grid-template-columns:75px 1fr; gap:5px 10px; margin:0; font:.86rem Verdana,sans-serif; }
        dt { color:var(--muted); } dd { margin:0; }
        form.filters, form.quick, form.status { display:flex; flex-wrap:wrap; gap:10px; align-items:end; }
        .admin { display:grid; grid-template-columns:repeat(auto-fit,minmax(170px,1fr)); gap:12px; align-items:end; }
        label { display:grid; gap:4px; }
        input, select { width:100%; border:1px solid #c6d1ca; border-radius:6px; padding:9px; background:#fff; color:var(--ink); }
        .span { grid-column:1/-1; }
        table { width:100%; border-collapse:collapse; background:#fff; }
        th, td { border-bottom:1px solid var(--line); padding:9px; text-align:left; vertical-align:top; }
        th { background:#f4f7f2; color:var(--muted); font:.78rem Verdana,sans-serif; }
        .stack { display:grid; gap:14px; }
        .heading { display:flex; justify-content:space-between; gap:10px; align-items:baseline; margin-bottom:10px; }
        .actions { display:flex; gap:8px; margin-top:10px; }
        .notice { padding:12px 14px; border-radius:7px; margin-bottom:14px; font:bold .86rem Verdana,sans-serif; }
        .ok { background:#e8f4ea; border:1px solid #a8d2ae; color:#175b2a; }
        .err { background:#fff0ea; border:1px solid #e7b39f; color:#8a2b13; white-space:pre-wrap; }
        footer { color:var(--muted); font:.78rem Verdana,sans-serif; padding:22px 0 34px; }
        @media (max-width:700px){ header,.hero{grid-template-columns:1fr;display:grid}.metrics{grid-template-columns:1fr 1fr} nav a,button{width:100%;text-align:center} }
    </style>
</head>
<body>
<header><div><p class="small">AdventureWorksLT converted to PostgreSQL</p><h1>PHP commerce operations</h1></div><p class="small">Apache + PDO + PostgreSQL auth</p></header>
<nav>
<?php foreach ($validViews as $item) { ?><a class="<?php echo $view === $item ? 'active' : ''; ?>" href="?view=<?php echo h($item); ?>"><?php echo h(ucfirst($item)); ?></a><?php } ?>
</nav>
<main>
<?php if ($message) { ?><div class="notice ok"><?php echo h($message); ?></div><?php } ?>
<?php if ($error) { ?><div class="notice err">PostgreSQL error: <?php echo h($error); ?></div><?php } ?>
<section class="metrics"><div class="metric"><span>Products</span><strong><?php echo h($stats['products']); ?></strong></div><div class="metric"><span>Customers</span><strong><?php echo h($stats['customers']); ?></strong></div><div class="metric"><span>Orders</span><strong><?php echo h($stats['orders']); ?></strong></div><div class="metric"><span>Revenue</span><strong><?php echo money($stats['revenue']); ?></strong></div></section>

<?php if ($view === 'catalog') {
    $search = trim(isset($_GET['search']) ? $_GET['search'] : '');
    $category = isset($_GET['category']) ? (int)$_GET['category'] : 0;
    $catalog = rows("SELECT p.* FROM saleslt.v_storefront_catalog p JOIN saleslt.product source ON source.product_id=p.product_id WHERE source.sell_end_date IS NULL AND (? = 0 OR source.product_category_id = ?) AND (? = '' OR p.name ILIKE '%' || ? || '%' OR p.product_number ILIKE '%' || ? || '%' OR p.description ILIKE '%' || ? || '%') ORDER BY p.category_name, p.name", array($category, $category, $search, $search, $search, $search));
?>
<section class="panel hero"><div><p class="small">PostgreSQL AdventureWorks storefront</p><h2>Converted schema, same commerce workflow</h2><p>This PHP page uses PDO and the PostgreSQL `saleslt` schema to browse products, create orders, and exercise database authentication.</p></div></section>
<section class="panel"><form class="filters" method="get"><input type="hidden" name="view" value="catalog" /><label>Search<input name="search" value="<?php echo h($search); ?>" /></label><label>Category<select name="category"><option value="0">All categories</option><?php echo options(categories(), 'product_category_id', 'label', $category); ?></select></label><button type="submit">Filter</button></form></section>
<section class="grid">
<?php foreach ($catalog as $product) { ?><article class="card"><span class="pill"><?php echo h($product['category_name']); ?></span><h3><?php echo h($product['name']); ?></h3><p><?php echo h($product['description']); ?></p><dl><dt>Model</dt><dd><?php echo h($product['product_model']); ?></dd><dt>Number</dt><dd><?php echo h($product['product_number']); ?></dd><dt>Color</dt><dd><?php echo h($product['color']); ?></dd></dl><form class="quick" method="post"><input type="hidden" name="action" value="createOrder" /><input type="hidden" name="product_id" value="<?php echo h($product['product_id']); ?>" /><strong><?php echo money($product['list_price']); ?></strong><select name="customer_id"><?php echo options(customers(), 'customer_id', 'label'); ?></select><input name="quantity" type="number" min="1" value="1" /><button type="submit">Create order</button></form></article><?php } ?>
</section>
<?php } elseif ($view === 'products') { $items = rows("SELECT p.*, COALESCE(c.name,'Uncategorized') AS category_name, COALESCE(pm.name,'Legacy model') AS model_name, COALESCE(d.description,'') AS description FROM saleslt.product p LEFT JOIN saleslt.product_category c ON c.product_category_id=p.product_category_id LEFT JOIN saleslt.product_model pm ON pm.product_model_id=p.product_model_id LEFT JOIN LATERAL (SELECT pd.description FROM saleslt.product_model_product_description x JOIN saleslt.product_description pd ON pd.product_description_id=x.product_description_id WHERE x.product_model_id=p.product_model_id LIMIT 1) d ON true ORDER BY p.sell_end_date NULLS FIRST, p.name"); ?>
<section class="panel"><h2>Product administration</h2><form class="admin" method="post"><input type="hidden" name="action" value="saveProduct" /><label>Name<input name="name" required maxlength="50" /></label><label>Number<input name="product_number" required maxlength="25" /></label><label>Model<input name="model_name" required maxlength="50" /></label><label>Category<select name="product_category_id"><?php echo options(categories(), 'product_category_id', 'label'); ?></select></label><label>Color<input name="color" maxlength="15" /></label><label>Size<input name="size" maxlength="5" /></label><label>Weight<input name="weight" type="number" step="0.01" /></label><label>List price<input name="list_price" type="number" step="0.01" required /></label><label class="span">Description<input name="description" required maxlength="400" /></label><button type="submit">Add product</button></form></section>
<section class="stack"><?php foreach ($items as $item) { ?><article class="edit-card"><form method="post"><input type="hidden" name="action" value="saveProduct" /><input type="hidden" name="product_id" value="<?php echo h($item['product_id']); ?>" /><div class="heading"><strong><?php echo h($item['name']); ?></strong><span class="small"><?php echo h($item['product_number']); ?></span></div><div class="admin"><label>Name<input name="name" value="<?php echo h($item['name']); ?>" /></label><label>Number<input name="product_number" value="<?php echo h($item['product_number']); ?>" /></label><label>Model<input name="model_name" value="<?php echo h($item['model_name']); ?>" /></label><label>Category<select name="product_category_id"><?php echo options(categories(), 'product_category_id', 'label', $item['product_category_id']); ?></select></label><label>Color<input name="color" value="<?php echo h($item['color']); ?>" /></label><label>Size<input name="size" value="<?php echo h($item['size']); ?>" /></label><label>Weight<input name="weight" type="number" step="0.01" value="<?php echo h($item['weight']); ?>" /></label><label>List price<input name="list_price" type="number" step="0.01" value="<?php echo h($item['list_price']); ?>" /></label><label class="span">Description<input name="description" value="<?php echo h($item['description']); ?>" /></label></div><div class="actions"><button type="submit">Save</button></form><form method="post"><input type="hidden" name="action" value="retireProduct" /><input type="hidden" name="product_id" value="<?php echo h($item['product_id']); ?>" /><button type="submit">Retire</button></form></div></article><?php } ?></section>
<?php } elseif ($view === 'customers') { $customerRows = rows('SELECT * FROM saleslt.customer ORDER BY last_name, first_name'); $addressRows = rows("SELECT c.last_name, c.first_name, ca.address_type, a.address_line1, a.city, a.state_province, a.postal_code FROM saleslt.customer c JOIN saleslt.customer_address ca ON ca.customer_id=c.customer_id JOIN saleslt.address a ON a.address_id=ca.address_id ORDER BY c.last_name"); ?>
<section class="panel"><h2>Customer management</h2><form class="admin" method="post"><input type="hidden" name="action" value="saveCustomer" /><label>First<input name="first_name" required /></label><label>Last<input name="last_name" required /></label><label>Company<input name="company_name" /></label><label>Email<input name="email_address" type="email" required /></label><label>Phone<input name="phone" /></label><button type="submit">Add customer</button></form></section>
<section class="stack"><?php foreach ($customerRows as $customer) { ?><article class="edit-card"><form method="post"><input type="hidden" name="action" value="saveCustomer" /><input type="hidden" name="customer_id" value="<?php echo h($customer['customer_id']); ?>" /><div class="admin"><label>First<input name="first_name" value="<?php echo h($customer['first_name']); ?>" /></label><label>Last<input name="last_name" value="<?php echo h($customer['last_name']); ?>" /></label><label>Company<input name="company_name" value="<?php echo h($customer['company_name']); ?>" /></label><label>Email<input name="email_address" value="<?php echo h($customer['email_address']); ?>" /></label><label>Phone<input name="phone" value="<?php echo h($customer['phone']); ?>" /></label><button type="submit">Save</button></div></form></article><?php } ?></section>
<section class="panel"><h2>Add address</h2><form class="admin" method="post"><input type="hidden" name="action" value="saveAddress" /><label>Customer<select name="customer_id"><?php echo options(customers(), 'customer_id', 'label'); ?></select></label><label>Type<input name="address_type" value="Shipping" required /></label><label>Line 1<input name="address_line1" required /></label><label>Line 2<input name="address_line2" /></label><label>City<input name="city" required /></label><label>State<input name="state_province" required /></label><label>Postal<input name="postal_code" required /></label><label>Country<input name="country_region" value="United States" required /></label><button type="submit">Add address</button></form><table><tr><th>Customer</th><th>Type</th><th>Address</th><th>City</th><th>Postal</th></tr><?php foreach ($addressRows as $address) { ?><tr><td><?php echo h($address['last_name'] . ', ' . $address['first_name']); ?></td><td><?php echo h($address['address_type']); ?></td><td><?php echo h($address['address_line1']); ?></td><td><?php echo h($address['city'] . ', ' . $address['state_province']); ?></td><td><?php echo h($address['postal_code']); ?></td></tr><?php } ?></table></section>
<?php } elseif ($view === 'orders') { $orderRows = rows("SELECT h.*, c.first_name, c.last_name, c.company_name FROM saleslt.sales_order_header h JOIN saleslt.customer c ON c.customer_id=h.customer_id ORDER BY h.sales_order_id DESC"); $detailRows = rows("SELECT d.sales_order_id, p.name, d.order_qty, d.unit_price, d.line_total FROM saleslt.sales_order_detail d JOIN saleslt.product p ON p.product_id=d.product_id ORDER BY d.sales_order_id DESC, d.sales_order_detail_id"); ?>
<section class="panel"><h2>Create order</h2><form class="admin" method="post"><input type="hidden" name="action" value="createOrder" /><label>Customer<select name="customer_id"><?php echo options(customers(), 'customer_id', 'label'); ?></select></label><label>Product<select name="product_id"><?php echo options(products(), 'product_id', 'label'); ?></select></label><label>Quantity<input name="quantity" type="number" min="1" value="1" /></label><button type="submit">Create order</button></form></section>
<section class="stack"><?php foreach ($orderRows as $order) { ?><article class="order-card"><div class="heading"><strong><?php echo h($order['sales_order_number']); ?></strong><span><?php echo h($order['last_name'] . ', ' . $order['first_name']); ?> - <?php echo money($order['total_due']); ?></span></div><form class="status" method="post"><input type="hidden" name="action" value="updateOrderStatus" /><input type="hidden" name="sales_order_id" value="<?php echo h($order['sales_order_id']); ?>" /><select name="status"><?php foreach (array(1=>'In process',2=>'Approved',3=>'Backordered',4=>'Rejected',5=>'Shipped',6=>'Cancelled') as $code=>$label) { ?><option value="<?php echo $code; ?>" <?php echo (int)$order['status']===$code?'selected':''; ?>><?php echo h($label); ?></option><?php } ?></select><button type="submit">Update</button></form><table><tr><th>Product</th><th>Qty</th><th>Unit</th><th>Total</th></tr><?php foreach ($detailRows as $detail) { if ((int)$detail['sales_order_id'] === (int)$order['sales_order_id']) { ?><tr><td><?php echo h($detail['name']); ?></td><td><?php echo h($detail['order_qty']); ?></td><td><?php echo money($detail['unit_price']); ?></td><td><?php echo money($detail['line_total']); ?></td></tr><?php }} ?></table></article><?php } ?></section>
<?php } else { $categoryRevenue = rows("SELECT COALESCE(c.name,'Uncategorized') AS category_name, SUM(d.order_qty) AS units, SUM(d.line_total) AS revenue FROM saleslt.sales_order_detail d JOIN saleslt.product p ON p.product_id=d.product_id LEFT JOIN saleslt.product_category c ON c.product_category_id=p.product_category_id GROUP BY c.name ORDER BY revenue DESC"); $customerRevenue = rows("SELECT c.last_name, c.first_name, COUNT(h.sales_order_id) AS orders, SUM(h.total_due) AS revenue FROM saleslt.customer c JOIN saleslt.sales_order_header h ON h.customer_id=c.customer_id GROUP BY c.last_name, c.first_name ORDER BY revenue DESC"); ?>
<section class="grid"><article class="panel"><h2>Revenue by category</h2><table><tr><th>Category</th><th>Units</th><th>Revenue</th></tr><?php foreach ($categoryRevenue as $row) { ?><tr><td><?php echo h($row['category_name']); ?></td><td><?php echo h($row['units']); ?></td><td><?php echo money($row['revenue']); ?></td></tr><?php } ?></table></article><article class="panel"><h2>Customer revenue</h2><table><tr><th>Customer</th><th>Orders</th><th>Revenue</th></tr><?php foreach ($customerRevenue as $row) { ?><tr><td><?php echo h($row['last_name'] . ', ' . $row['first_name']); ?></td><td><?php echo h($row['orders']); ?></td><td><?php echo money($row['revenue']); ?></td></tr><?php } ?></table></article></section>
<?php } ?>
</main>
<footer>Host: <?php echo h(gethostname()); ?> &middot; Database: <?php echo h($dbName); ?> &middot; User: <?php echo h($dbUser); ?></footer>
</body>
</html>
PHP

sudo WEB_DB="${WEB_DB}" WEB_USER="${WEB_USER}" WEB_PASSWORD="${WEB_PASSWORD}" perl -0pi -e 's/__WEB_DB__/$ENV{WEB_DB}/g; s/__WEB_USER__/$ENV{WEB_USER}/g; s/__WEB_PASSWORD__/$ENV{WEB_PASSWORD}/g' /var/www/html/index.php
sudo chown www-data:www-data /var/www/html/index.php
sudo rm -f /var/www/html/index.html
sudo systemctl enable --now apache2
LEGACY_PHP_STOREFRONT_REMOVED

echo 'Installing Java/Tomcat AdventureWorks storefront fronted by Apache'
APP_DIR="${TOMCAT_BASE}/webapps/arcbox"
JDBC_JAR=$(find /usr/share/java -maxdepth 1 -name 'postgresql*.jar' -print | sort | head -n 1)
if [[ -z "${JDBC_JAR}" ]]; then
    echo 'PostgreSQL JDBC driver jar was not found under /usr/share/java' >&2
    exit 1
fi

sudo rm -rf "${APP_DIR}"
sudo install -d -m 755 "${APP_DIR}/WEB-INF/lib" "${APP_DIR}/META-INF"
sudo cp "${JDBC_JAR}" "${APP_DIR}/WEB-INF/lib/postgresql.jar"

sudo tee "${APP_DIR}/WEB-INF/db.properties" > /dev/null <<EOF
db=${WEB_DB}
user=${WEB_USER}
password=${WEB_PASSWORD}
EOF

if [[ "${TOMCAT_PACKAGE}" == 'tomcat10' ]]; then
    sudo tee "${APP_DIR}/WEB-INF/web.xml" > /dev/null <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_5_0.xsd" version="5.0">
  <display-name>ArcBox AdventureWorks Java Storefront</display-name>
  <welcome-file-list>
    <welcome-file>index.jsp</welcome-file>
  </welcome-file-list>
</web-app>
XML
else
    sudo tee "${APP_DIR}/WEB-INF/web.xml" > /dev/null <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd" version="4.0">
  <display-name>ArcBox AdventureWorks Java Storefront</display-name>
  <welcome-file-list>
    <welcome-file>index.jsp</welcome-file>
  </welcome-file-list>
</web-app>
XML
fi

sudo tee "${APP_DIR}/index.jsp" > /dev/null <<'JSP'
<%@ page import="java.sql.*,java.util.*,java.math.BigDecimal,java.text.NumberFormat,java.io.InputStream" %>
<%!
String h(Object value) {
    if (value == null) {
        return "";
    }
    return String.valueOf(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
}

String money(Object value) {
    if (value == null) {
        return "$0.00";
    }
    return NumberFormat.getCurrencyInstance(Locale.US).format(value);
}

int asInt(String raw, int fallback) {
    try {
        return Integer.parseInt(raw);
    } catch (Exception ex) {
        return fallback;
    }
}

void bind(PreparedStatement statement, Object... values) throws SQLException {
    for (int i = 0; i < values.length; i++) {
        statement.setObject(i + 1, values[i]);
    }
}

List<Map<String,Object>> rows(Connection connection, String sql, Object... values) throws SQLException {
    List<Map<String,Object>> output = new ArrayList<Map<String,Object>>();
    try (PreparedStatement statement = connection.prepareStatement(sql)) {
        bind(statement, values);
        try (ResultSet result = statement.executeQuery()) {
            ResultSetMetaData metadata = result.getMetaData();
            while (result.next()) {
                Map<String,Object> row = new LinkedHashMap<String,Object>();
                for (int i = 1; i <= metadata.getColumnCount(); i++) {
                    row.put(metadata.getColumnLabel(i).toLowerCase(Locale.ROOT), result.getObject(i));
                }
                output.add(row);
            }
        }
    }
    return output;
}

Object scalar(Connection connection, String sql, Object... values) throws SQLException {
    try (PreparedStatement statement = connection.prepareStatement(sql)) {
        bind(statement, values);
        try (ResultSet result = statement.executeQuery()) {
            return result.next() ? result.getObject(1) : null;
        }
    }
}

int scalarInt(Connection connection, String sql, Object... values) throws SQLException {
    Object value = scalar(connection, sql, values);
    return value instanceof Number ? ((Number)value).intValue() : asInt(String.valueOf(value), 0);
}

void execute(Connection connection, String sql, Object... values) throws SQLException {
    try (PreparedStatement statement = connection.prepareStatement(sql)) {
        bind(statement, values);
        statement.executeUpdate();
    }
}

String statusName(Object value) {
    int status = value instanceof Number ? ((Number)value).intValue() : asInt(String.valueOf(value), 0);
    switch (status) {
        case 1: return "In process";
        case 2: return "Approved";
        case 3: return "Backordered";
        case 4: return "Rejected";
        case 5: return "Shipped";
        case 6: return "Cancelled";
        default: return "Unknown";
    }
}

String nav(String currentView, String targetView, String label) {
    return "<a" + (currentView.equals(targetView) ? " class='active'" : "") + " href='?view=" + h(targetView) + "'>" + h(label) + "</a>";
}
%>
<%
request.setCharacterEncoding("UTF-8");

Set<String> validViews = new HashSet<String>(Arrays.asList("catalog", "orders", "customers", "reports"));
String view = request.getParameter("view") == null ? "catalog" : request.getParameter("view").toLowerCase(Locale.ROOT);
if (!validViews.contains(view)) {
    view = "catalog";
}

String search = request.getParameter("search") == null ? "" : request.getParameter("search").trim();
int categoryId = asInt(request.getParameter("category"), 0);
String message = "";
String error = "";

Map<String,Object> stats = new HashMap<String,Object>();
List<Map<String,Object>> categories = Collections.emptyList();
List<Map<String,Object>> customers = Collections.emptyList();
List<Map<String,Object>> catalog = Collections.emptyList();
List<Map<String,Object>> orders = Collections.emptyList();
List<Map<String,Object>> details = Collections.emptyList();
List<Map<String,Object>> categoryRevenue = Collections.emptyList();
List<Map<String,Object>> customerRevenue = Collections.emptyList();

Properties properties = new Properties();
try (InputStream propertiesStream = application.getResourceAsStream("/WEB-INF/db.properties")) {
    if (propertiesStream == null) {
        throw new IllegalStateException("Missing WEB-INF/db.properties");
    }
    properties.load(propertiesStream);
}

String dbName = properties.getProperty("db");
String dbUser = properties.getProperty("user");
String dbPassword = properties.getProperty("password");

try {
    Class.forName("org.postgresql.Driver");
    try (Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/" + dbName, dbUser, dbPassword)) {
        if ("POST".equalsIgnoreCase(request.getMethod())) {
            String action = request.getParameter("action") == null ? "" : request.getParameter("action");
            if ("createOrder".equals(action)) {
                int customerId = asInt(request.getParameter("customer_id"), 0);
                int productId = asInt(request.getParameter("product_id"), 0);
                int quantity = asInt(request.getParameter("quantity"), 1);
                if (customerId == 0 || productId == 0 || quantity < 1) {
                    throw new IllegalArgumentException("Choose a customer, product, and positive quantity.");
                }
                Object addressId = scalar(connection, "SELECT address_id FROM saleslt.customer_address WHERE customer_id = ? ORDER BY address_id LIMIT 1", customerId);
                if (addressId == null) {
                    throw new IllegalStateException("The selected customer needs an address before an order can be created.");
                }
                Object unitPrice = scalar(connection, "SELECT list_price FROM saleslt.product WHERE product_id = ?", productId);
                int orderId = scalarInt(connection, "INSERT INTO saleslt.sales_order_header (customer_id, ship_to_address_id, bill_to_address_id, purchase_order_number, account_number, status, comment) VALUES (?, ?, ?, ?, '10-4020-JAVA', 1, 'Created from Java Tomcat storefront') RETURNING sales_order_id", customerId, addressId, addressId, "JAVA-" + Long.toString(System.currentTimeMillis()));
                execute(connection, "INSERT INTO saleslt.sales_order_detail (sales_order_id, product_id, order_qty, unit_price) VALUES (?, ?, ?, ?)", orderId, productId, quantity, unitPrice);
                view = "orders";
                message = "Order created.";
            } else if ("updateOrderStatus".equals(action)) {
                int orderId = asInt(request.getParameter("sales_order_id"), 0);
                int status = asInt(request.getParameter("status"), 0);
                if (orderId == 0 || status < 1 || status > 6) {
                    throw new IllegalArgumentException("Choose a valid order status.");
                }
                execute(connection, "UPDATE saleslt.sales_order_header SET status = ?, ship_date = CASE WHEN ? >= 5 THEN COALESCE(ship_date, now()) ELSE ship_date END, modified_date = now() WHERE sales_order_id = ?", status, status, orderId);
                view = "orders";
                message = "Order status updated.";
            }
        }

        List<Map<String,Object>> statRows = rows(connection, "SELECT (SELECT count(*) FROM saleslt.product WHERE sell_end_date IS NULL) AS products, (SELECT count(*) FROM saleslt.customer) AS customers, (SELECT count(*) FROM saleslt.sales_order_header) AS orders, (SELECT coalesce(sum(total_due), 0) FROM saleslt.sales_order_header) AS revenue");
        stats = statRows.isEmpty() ? stats : statRows.get(0);
        categories = rows(connection, "SELECT c.product_category_id, COALESCE(parent.name || ' / ', '') || c.name AS label FROM saleslt.product_category c LEFT JOIN saleslt.product_category parent ON parent.product_category_id = c.parent_product_category_id ORDER BY label");
        customers = rows(connection, "SELECT customer_id, last_name || ', ' || first_name || COALESCE(' - ' || company_name, '') AS label FROM saleslt.customer ORDER BY last_name, first_name");

        catalog = rows(connection, "SELECT p.product_id, p.name, p.product_number, COALESCE(p.color, 'Any') AS color, COALESCE(p.size, '') AS size, p.list_price, COALESCE(p.category_name, 'Uncategorized') AS category_name, COALESCE(p.product_model, 'Legacy model') AS product_model, COALESCE(p.description, 'AdventureWorks catalog item') AS description FROM saleslt.v_storefront_catalog p JOIN saleslt.product source ON source.product_id = p.product_id WHERE source.sell_end_date IS NULL AND (? = 0 OR source.product_category_id = ?) AND (? = '' OR p.name ILIKE '%' || ? || '%' OR p.product_number ILIKE '%' || ? || '%' OR p.description ILIKE '%' || ? || '%') ORDER BY p.category_name, p.name", categoryId, categoryId, search, search, search, search);
        orders = rows(connection, "SELECT h.sales_order_id, h.sales_order_number, h.purchase_order_number, h.order_date, h.status, h.total_due, c.first_name, c.last_name, c.company_name FROM saleslt.sales_order_header h JOIN saleslt.customer c ON c.customer_id = h.customer_id ORDER BY h.sales_order_id DESC");
        details = rows(connection, "SELECT d.sales_order_id, p.name, d.order_qty, d.unit_price, d.line_total FROM saleslt.sales_order_detail d JOIN saleslt.product p ON p.product_id = d.product_id ORDER BY d.sales_order_id DESC, d.sales_order_detail_id");
        categoryRevenue = rows(connection, "SELECT COALESCE(c.name, 'Uncategorized') AS category_name, SUM(d.order_qty) AS units, SUM(d.line_total) AS revenue FROM saleslt.sales_order_detail d JOIN saleslt.product p ON p.product_id = d.product_id LEFT JOIN saleslt.product_category c ON c.product_category_id = p.product_category_id GROUP BY c.name ORDER BY revenue DESC");
        customerRevenue = rows(connection, "SELECT c.last_name, c.first_name, COUNT(h.sales_order_id) AS orders, SUM(h.total_due) AS revenue FROM saleslt.customer c JOIN saleslt.sales_order_header h ON h.customer_id = c.customer_id GROUP BY c.last_name, c.first_name ORDER BY revenue DESC");
    }
} catch (Exception ex) {
    error = ex.getMessage();
}
%>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>AdventureWorks Java Storefront</title>
    <style>
        :root { --ink:#172027; --muted:#62706d; --line:#d4ddd8; --paper:#fbfaf2; --panel:#fff; --brand:#245f56; --accent:#b95734; --soft:#eef6ef; }
        * { box-sizing:border-box; }
        body { margin:0; color:var(--ink); font-family:Georgia,"Times New Roman",serif; background:linear-gradient(135deg,#fbfaf2 0%,#eef6ef 52%,#f8e6dc 100%); }
        header, nav, main, footer { width:min(1180px,calc(100% - 30px)); margin:auto; }
        header { padding:30px 0 12px; display:grid; grid-template-columns:1fr auto; gap:18px; align-items:end; border-bottom:1px solid var(--line); }
        h1 { margin:0; font-size:clamp(2rem,5vw,4rem); line-height:1; }
        h2, h3 { margin:0 0 12px; }
        p { color:var(--muted); line-height:1.5; }
        nav { display:flex; flex-wrap:wrap; gap:8px; padding:18px 0; }
        nav a, button { border:1px solid var(--brand); border-radius:7px; padding:10px 14px; background:#fff; color:var(--brand); text-decoration:none; font:bold .86rem Verdana,sans-serif; cursor:pointer; }
        nav a.active, button { background:var(--brand); color:#fff; }
        .metrics { display:grid; grid-template-columns:repeat(4,minmax(130px,1fr)); gap:12px; margin-bottom:18px; }
        .metric, .panel, .card, .order-card { background:rgba(255,255,255,.92); border:1px solid var(--line); border-radius:8px; box-shadow:0 12px 30px rgba(24,33,31,.08); }
        .metric { padding:16px; }
        .metric span, label, .pill, .small { color:var(--muted); font:.78rem Verdana,sans-serif; }
        .metric strong { display:block; font-size:1.8rem; margin-top:8px; }
        .panel { padding:20px; margin-bottom:16px; }
        .hero { display:grid; grid-template-columns:1fr auto; gap:18px; background:linear-gradient(120deg,#fff,var(--soft)); }
        .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:16px; }
        .card, .order-card { padding:16px; }
        .pill { display:inline-block; background:var(--soft); color:var(--brand); padding:5px 9px; border-radius:999px; margin-bottom:10px; }
        dl { display:grid; grid-template-columns:75px 1fr; gap:5px 10px; margin:0; font:.86rem Verdana,sans-serif; }
        dt { color:var(--muted); } dd { margin:0; }
        form.filters, form.quick, form.status { display:flex; flex-wrap:wrap; gap:10px; align-items:end; }
        input, select { width:100%; border:1px solid #c6d1ca; border-radius:6px; padding:9px; background:#fff; color:var(--ink); }
        label { display:grid; gap:4px; min-width:160px; }
        table { width:100%; border-collapse:collapse; background:#fff; }
        th, td { border-bottom:1px solid var(--line); padding:9px; text-align:left; vertical-align:top; }
        th { background:#f4f7f2; color:var(--muted); font:.78rem Verdana,sans-serif; }
        .stack { display:grid; gap:14px; }
        .heading { display:flex; justify-content:space-between; gap:10px; align-items:baseline; margin-bottom:10px; }
        .notice { padding:12px 14px; border-radius:7px; margin-bottom:14px; font:bold .86rem Verdana,sans-serif; }
        .ok { background:#e8f4ea; border:1px solid #a8d2ae; color:#175b2a; }
        .err { background:#fff0ea; border:1px solid #e7b39f; color:#8a2b13; white-space:pre-wrap; }
        footer { color:var(--muted); font:.78rem Verdana,sans-serif; padding:22px 0 34px; }
        @media (max-width:700px){ header,.hero{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr} nav a,button{width:100%;text-align:center} }
    </style>
</head>
<body>
<header><div><p class="small">AdventureWorksLT on PostgreSQL</p><h1>Java commerce operations</h1></div><p class="small">Apache + Tomcat + JDBC</p></header>
<nav><%= nav(view, "catalog", "Catalog") %><%= nav(view, "orders", "Orders") %><%= nav(view, "customers", "Customers") %><%= nav(view, "reports", "Reports") %></nav>
<main>
<% if (!message.isEmpty()) { %><div class="notice ok"><%= h(message) %></div><% } %>
<% if (!error.isEmpty()) { %><div class="notice err">PostgreSQL error: <%= h(error) %></div><% } %>
<section class="metrics"><div class="metric"><span>Products</span><strong><%= h(stats.get("products")) %></strong></div><div class="metric"><span>Customers</span><strong><%= h(stats.get("customers")) %></strong></div><div class="metric"><span>Orders</span><strong><%= h(stats.get("orders")) %></strong></div><div class="metric"><span>Revenue</span><strong><%= money(stats.get("revenue")) %></strong></div></section>

<% if ("catalog".equals(view)) { %>
<section class="panel hero"><div><p class="small">PostgreSQL AdventureWorks storefront</p><h2>Converted catalog and order flow</h2><p>Browse products, place orders, and exercise the JDBC path through Tomcat.</p></div></section>
<section class="panel"><form class="filters" method="get"><input type="hidden" name="view" value="catalog" /><label>Search<input name="search" value="<%= h(search) %>" /></label><label>Category<select name="category"><option value="0">All categories</option><% for (Map<String,Object> category : categories) { %><option value="<%= h(category.get("product_category_id")) %>" <%= String.valueOf(category.get("product_category_id")).equals(String.valueOf(categoryId)) ? "selected" : "" %>><%= h(category.get("label")) %></option><% } %></select></label><button type="submit">Filter</button></form></section>
<section class="grid">
<% for (Map<String,Object> product : catalog) { %><article class="card"><span class="pill"><%= h(product.get("category_name")) %></span><h3><%= h(product.get("name")) %></h3><p><%= h(product.get("description")) %></p><dl><dt>Model</dt><dd><%= h(product.get("product_model")) %></dd><dt>Number</dt><dd><%= h(product.get("product_number")) %></dd><dt>Color</dt><dd><%= h(product.get("color")) %></dd></dl><form class="quick" method="post"><input type="hidden" name="action" value="createOrder" /><input type="hidden" name="product_id" value="<%= h(product.get("product_id")) %>" /><strong><%= money(product.get("list_price")) %></strong><select name="customer_id"><% for (Map<String,Object> customer : customers) { %><option value="<%= h(customer.get("customer_id")) %>"><%= h(customer.get("label")) %></option><% } %></select><input name="quantity" type="number" min="1" value="1" /><button type="submit">Create order</button></form></article><% } %>
</section>
<% } else if ("orders".equals(view)) { %>
<section class="stack">
<% for (Map<String,Object> order : orders) { %><article class="order-card"><div class="heading"><strong><%= h(order.get("sales_order_number")) %></strong><span><%= h(order.get("last_name")) %>, <%= h(order.get("first_name")) %> - <%= money(order.get("total_due")) %></span></div><form class="status" method="post"><input type="hidden" name="action" value="updateOrderStatus" /><input type="hidden" name="sales_order_id" value="<%= h(order.get("sales_order_id")) %>" /><select name="status"><% for (int status = 1; status <= 6; status++) { %><option value="<%= status %>" <%= statusName(order.get("status")).equals(statusName(status)) ? "selected" : "" %>><%= h(statusName(status)) %></option><% } %></select><button type="submit">Update</button></form><table><tr><th>Product</th><th>Qty</th><th>Unit</th><th>Total</th></tr><% for (Map<String,Object> detail : details) { if (String.valueOf(detail.get("sales_order_id")).equals(String.valueOf(order.get("sales_order_id")))) { %><tr><td><%= h(detail.get("name")) %></td><td><%= h(detail.get("order_qty")) %></td><td><%= money(detail.get("unit_price")) %></td><td><%= money(detail.get("line_total")) %></td></tr><% }} %></table></article><% } %>
</section>
<% } else if ("customers".equals(view)) { %>
<section class="panel"><h2>Customers</h2><table><tr><th>Name</th><th>Customer ID</th></tr><% for (Map<String,Object> customer : customers) { %><tr><td><%= h(customer.get("label")) %></td><td><%= h(customer.get("customer_id")) %></td></tr><% } %></table></section>
<% } else { %>
<section class="grid"><article class="panel"><h2>Revenue by category</h2><table><tr><th>Category</th><th>Units</th><th>Revenue</th></tr><% for (Map<String,Object> row : categoryRevenue) { %><tr><td><%= h(row.get("category_name")) %></td><td><%= h(row.get("units")) %></td><td><%= money(row.get("revenue")) %></td></tr><% } %></table></article><article class="panel"><h2>Customer revenue</h2><table><tr><th>Customer</th><th>Orders</th><th>Revenue</th></tr><% for (Map<String,Object> row : customerRevenue) { %><tr><td><%= h(row.get("last_name")) %>, <%= h(row.get("first_name")) %></td><td><%= h(row.get("orders")) %></td><td><%= money(row.get("revenue")) %></td></tr><% } %></table></article></section>
<% } %>
</main>
<footer>Host: <%= h(java.net.InetAddress.getLocalHost().getHostName()) %> &middot; Database: <%= h(dbName) %> &middot; Runtime: <%= h(System.getProperty("java.runtime.version")) %></footer>
</body>
</html>
JSP

TOMCAT_USER=$(id -un tomcat 2>/dev/null || echo root)
TOMCAT_GROUP=$(id -gn "${TOMCAT_USER}" 2>/dev/null || echo root)
sudo chown -R "${TOMCAT_USER}:${TOMCAT_GROUP}" "${APP_DIR}"
sudo chmod 640 "${APP_DIR}/WEB-INF/db.properties"

sudo rm -f /var/www/html/index.php /var/www/html/index.html
sudo a2enmod proxy proxy_http headers >/dev/null
sudo tee /etc/apache2/sites-available/arcbox-tomcat.conf > /dev/null <<'APACHE'
<VirtualHost *:80>
    ServerName arcbox-java.local
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    ProxyPass / http://127.0.0.1:8080/arcbox/
    ProxyPassReverse / http://127.0.0.1:8080/arcbox/
    ErrorLog ${APACHE_LOG_DIR}/arcbox-tomcat-error.log
    CustomLog ${APACHE_LOG_DIR}/arcbox-tomcat-access.log combined
</VirtualHost>
APACHE
sudo a2dissite 000-default >/dev/null 2>&1 || true
sudo a2ensite arcbox-tomcat >/dev/null
sudo systemctl enable --now "${TOMCAT_SERVICE}"
sudo systemctl restart "${TOMCAT_SERVICE}"

for attempt in {1..30}; do
    if curl -fsS http://127.0.0.1:8080/arcbox/ >/dev/null; then
        break
    fi
    echo "Waiting for Tomcat application startup (${attempt}/30)"
    sleep 5
done
curl -fsS http://127.0.0.1:8080/arcbox/ >/dev/null

sudo systemctl restart apache2
curl -fsS http://127.0.0.1/ >/dev/null
sudo ufw allow 'Apache' >/dev/null 2>&1 || true
echo 'PostgreSQL AdventureWorksLT schema and Java/Tomcat storefront are running behind Apache'
